### ISSUE TITLE
Create a Hello World Flutter App

### ISSUE THREAD

**Issue by mdzh10** [mdzh10/FinBot-AI-Powered-Chatbot-For-Personal-Finance-Management#12]

**Comment by Sriramrajivkarri12** [comment]
Getting the hello world flutter app to run was a big issue. Writing everything was not a big task at all, but it only took a lot of time to know the proper dependencies to run. 

After a few days of trying, I went back to the team to see what solutions everyone had run to fix this issue.

**Comment by ruthvikbairaboina** [comment]
Created the Hello World app in Flutter. It wasn’t easy at first, especially with some of the setup steps, but I managed to get through it.

**Comment by vijaysai1102** [comment]
I created a basic flutter app to understand how to work with flutter. Flutter uses dart programming language and it's very new to me, so I learned the basics of dart language to create the basic app. I used YouTube as a reference to create this app. I was stuck many times before expecting the app successfully because there were so many dependencies that were missing, I figured out all of them and executed my basic flutter app successfully. I would say it's a great learning.
